# syntax=docker/dockerfile:1.4
FROM alpine AS builder

LABEL org.opencontainers.image.source=https://github.com/lusniam/pawcho6

RUN apk add --no-cache bash git openssh

RUN mkdir -m 700 /root/.ssh; \
  touch -m 600 /root/.ssh/known_hosts; \
  ssh-keyscan github.com > /root/.ssh/known_hosts

RUN --mount=type=ssh git clone git@github.com:lusniam/pawcho6.git

FROM nginx:alpine

LABEL org.opencontainers.image.source=https://github.com/lusniam/pawcho6

ARG VERSION="1.0.0"

COPY --from=builder /pawcho6/index.sh /app/index.sh
RUN chmod +x /app/index.sh && /app/index.sh

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
    CMD curl -f http://localhost/ || exit 1

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]